spring.application.name=demo
spring.security.oauth2.client.registration.github.client-id=Ov23liYYqM7TAWYKcmiO
spring.security.oauth2.client.registration.github.client-secret=438a175d6aa978c6d6cc5d88c05f344a605e5322
spring.security.oauth2.client.registration.github.scope=user:email
